notifications:
  email: false
  
rvm:
  - 2.1.2

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
cache: bundler

before_script:
- bundle exec rake

script: bundle exec rake spec 

after_success:
  coveralls