notifications:
  email: false

rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
cache: bundler

before_script:
- bundle exec rake

after_success:
  coveralls
