notifications:
  email: false
  
rvm:
  - 2.1.4
  - 2.1.2
  - 2.0.0
  - 1.9.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
cache: bundler

before_script:
- bundle exec rake

after_success:
  coveralls